"""Add agent_proposals and agent_configs tables for the autonomous agent loop.

Revision ID: 008
Create Date: 2026-04-11
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSONB

revision = "008"
down_revision = "007"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Agent proposals — generated by ObserverAgent + PlannerAgent
    op.create_table(
        "agent_proposals",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, index=True),
        sa.Column("pattern_type", sa.String(100), nullable=False, index=True),
        sa.Column("title", sa.String(500), nullable=False),
        sa.Column("description", sa.Text, nullable=False),
        sa.Column("suggested_action", sa.Text, nullable=False),
        sa.Column("tool", sa.String(100), nullable=False),
        sa.Column("confidence", sa.Float, nullable=False, server_default="0.5"),
        sa.Column("priority", sa.String(20), nullable=False, server_default="'medium'"),
        sa.Column("status", sa.String(20), nullable=False, server_default="'pending'", index=True),
        sa.Column("entity_ids", JSONB, server_default="[]"),
        sa.Column("context_snapshot", JSONB, server_default="{}"),
        sa.Column("proposed_for_user_id", UUID(as_uuid=True), sa.ForeignKey("users.id"), nullable=True),
        sa.Column("resolved_by_user_id", UUID(as_uuid=True), sa.ForeignKey("users.id", ondelete="SET NULL"), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delegation_id", UUID(as_uuid=True), sa.ForeignKey("delegations.id", ondelete="SET NULL"), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )

    # Agent config per org — thresholds, personality, learning state
    op.create_table(
        "agent_configs",
        sa.Column("id", UUID(as_uuid=True), primary_key=True, server_default=sa.text("gen_random_uuid()")),
        sa.Column("org_id", UUID(as_uuid=True), sa.ForeignKey("organizations.id", ondelete="CASCADE"), nullable=False, unique=True),
        sa.Column("enabled", sa.Boolean, server_default="true", nullable=False),
        sa.Column("mode", sa.String(20), server_default="'balanced'", nullable=False),
        sa.Column("confidence_threshold", sa.Float, server_default="0.6", nullable=False),
        sa.Column("auto_approve_threshold", sa.Float, server_default="0.95", nullable=False),
        sa.Column("patterns_enabled", JSONB, server_default='["stale_pr", "blocked_ticket", "missed_deadline", "unreviewed_pr", "idle_sprint_item", "knowledge_gap"]'),
        sa.Column("learning_data", JSONB, server_default="{}"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), onupdate=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table("agent_configs")
    op.drop_table("agent_proposals")
